config/routes.rb
Rails.application.routes.draw do

root 'pages#about'
get 'sign-up', to: 'students#new'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :courses
resources :students

post 'course_enroll', to: 'student_courses#create'
delete 'course_unenroll', to: 'student_courses#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_user

  helper_method :current_user, :logged_in?, :require_user
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
skip_before_action :require_user
before_action :set_course, only: [:edit, :show, :update, :destroy]
before_action :require_admin, only: [:new, :create, :destroy]
before_action :require_admin_or_teacher, only: [:edit, :update]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "#{@course.name} has been created!"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @course.update(course_params)
      flash[:notice] = "#{@course.name} has been updated"
      redirect_to courses_path
    else
      redirect_to course_path(@course)
    end
  end

  def show

  end

  def destroy
    @course.destroy
    flash[:notice] = "#{@course.name} has been deleted"
    redirect_to courses_path
  end

private
  def course_params
    params.require(:course).permit(:short_name, :name, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def require_admin
    if !logged_in? || !current_user.admin?
      flash[:notice] = "Only admin users can perform that action"
      redirect_to courses_path
    end
  end

  def require_admin_or_teacher
    if !logged_in? && (!current_user.teacher? || !current_user.admin?)
      flash[:notice] = "Only admin or teachers can perform that action"
      redirect_to courses_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user


  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :require_user, only: [:new, :create, :destroy]

  def new

  end

  def create
    student = Student.find_by(email: params[:session][:email].downcase)
    if student && student.authenticate(params[:session][:password])
      session[:student_id] = student.id
      flash[:notice] = "Welcome #{student.name}!"
      redirect_to student_path(student.id)
    else
      flash.now[:notice] = "There was something wrong with your credentials"
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
before_action :require_student, only: [:create, :destroy]


def create
   course_to_add = Course.find(params[:course_id])
   unless current_user.courses.include?(course_to_add)
     StudentCourse.create(course: course_to_add, student: current_user)
     flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
     redirect_to current_user
   else
     flash[:notice] = "Something was wrong with your enrollment."
     redirect_to courses_path
   end
end

def destroy
  course_to_delete = Course.find(params[:course_id])
  line_to_delete = StudentCourse.find_by(course: course_to_delete, student: current_user)
  StudentCourse.delete(line_to_delete.id)
  flash[:notice] = "#{current_user.name} has been unenrolled from #{course_to_delete.name}."
  redirect_to current_user
end

private
def require_admin
  if !logged_in? || !current_user.admin?
    flash[:notice] = "Only admin users can perform that action"
    redirect_to courses_path
  end
end

def require_student
  if !logged_in? || !current_user.student?
    flash[:notice] = "Only students users can enroll/unenroll from classes themselves from classes"
    redirect_to courses_path
  end
end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
skip_before_action :require_user, only: [:new, :create]
before_action :set_student, only: [:show, :edit, :update, :destroy]
before_action :require_same_student, only:[:edit, :update, :destroy]
before_action :require_admin, only:[:destory]

  def index
    @students = Student.where(student: true)
    @teachers = Student.where(teacher: true)
    @admins = Student.where(admin: true)
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      session[:student_id] = @student.id
      flash[:notice] = "You have successfully signed up #{@student.name}"
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated #{@student.name}"
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  def destroy
    @student.destroy
    flash[:notice] = "#{@student.name} has been deleted"
    redirect_to students_path
  end

private
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to edit_student_path(current_user)
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:notice] = "Only admin users can perform that action"
      redirect_to students_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_link
    if (logged_in?)
      link_to("Logout", logout_path, method: :delete)
    else
      link_to("Login", login_path)
    end
  end

  def account
    if (logged_in?)
      link_to("#{@current_user.name}'s Account", student_path(@current_user))
    else
      link_to("Sign Up", sign_up_path)
    end
  end


end

app/views/courses/_form.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @course.new_record? ? "Create New Course" : "Edit #{@course.name}" %></h3>
        <div class="row">
          <%= form_for(@course, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :short_name, placeholder: "Enter course short name", autofocus: true %>
                <%= f.label :short_name, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter course name" %>
                <%= f.label :name, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_area :description, placeholder: "Enter course description" %>
                <%= f.label :description, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@course.new_record? ? '<i class="material-icons right">arrow_forward</i>Create'.html_safe : '<i class="material-icons right">arrow_forward</i>Update'.html_safe, class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h1 class="center-align">Course Listing</h1>
    <% if logged_in? && current_user.admin? %>
      <a class="waves-effect waves-light btn red lighten-2" href="courses/new"><i class="material-icons left">add_circle</i>Add Course</a>
      <a class="waves-effect waves-light btn red lighten-2" href="#"><i class="material-icons left">add_circle</i>Enroll a Stduent</a>
    <% end %>
  </div>
</div>


<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && (current_user.admin? || current_user.teacher?) %>
            <%= link_to "View", course_path(course) %>
            <%= link_to "Edit", edit_course_path(course) %>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Delete", course_path(course), method: :delete, data: {confirm: "Arm you sure you want to delete this course?"} %>
            <% end %>
          <% elsif logged_in? && current_user.student?%>
            <% if logged_in? && !(current_user.courses.include?(course)) %>
              <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
            <% else %>
              <%= link_to "Unenroll", course_unenroll_path(course_id: course.id), method: :delete %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>New course page</h1>

app/views/courses/show.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= @course.short_name %>: <%= @course.name %></span>
      <p><%= @course.description %></p>
    </div>
    <div class="card-action">
      <% if logged_in? && (current_user.admin? || current_user.teacher?) %>
        <%= link_to "Edit Course", edit_course_path(@course) %>
        <% if logged_in? && current_user.admin? %>
          <%= link_to "Delete Course", course_path(@course), method: :delete, data: {confirm: "Arm you sure you want to delete this course?"} %>
        <% end %>
      <% elsif logged_in? && current_user.student?%>
        <% if logged_in? && !(current_user.courses.include?(@course)) %>
          <%= link_to "Enroll", course_enroll_path(course_id: @course.id), method: :post %>
        <% else %>
          <%= link_to "Unenroll", course_unenroll_path(course_id: @course.id), method: :delete %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><%= link_to 'Home', root_path, class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 Paul Tschudin
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to 'Tech University', root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= session_link %></li>
          <li><%= account %></li>
          <li><%= link_to 'Courses', courses_path %></li>
          <li><%= link_to 'Directory', students_path if logged_in? %></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%= session_link %></li>
          <li><%= account %></li>
          <li><%= link_to 'Courses', courses_path %></li>
          <li><%= link_to 'Directory', students_path  if logged_in? %></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnivApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %></strong>
            prohibited your profile from being created:
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student%>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? "Sign Up" : "Edit your Profile" %></h3>
        <div class="row">
          <%= form_for(@student, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :email, placeholder: "Enter your email" %>
                <%= f.label :email, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Enter your password" %>
                <%= f.label :password, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Enter your password" %>
                <%= f.label :password_confirmation, class: "active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Update'.html_safe, class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h1 class="center-align">Admin's Directory</h1>
  </div>
</div>


<div class="row">
  <% @admins.each do |admin| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= admin.name %></span>
          <p><%= admin.email %></p>
        </div>
        <div class="card-action">
          <%= link_to "View", student_path(admin) %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit", edit_student_path(admin) %>
            <% if current_user != admin %>
              <%= link_to "Delete", student_path(admin), method: :delete, data: {confirm: "Arm you sure you want to delete this student?"} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col s12">
    <h1 class="center-align">Teacher's Directory</h1>
  </div>
</div>


<div class="row">
  <% @teachers.each do |teacher| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= teacher.name %></span>
          <p><%= teacher.email %></p>
          <p>Course Enrollments:
          <% if teacher.courses.empty? %>
            None
          <% else %>
            <ul>
              <% teacher.courses.each do |course| %>
                <li><%= link_to "#{course.name}", course_path(course) %></li>
              <% end %>
            </ul>
          <% end %>
          </p>
        </div>
        <div class="card-action">
          <%= link_to "View", student_path(teacher) %>
          <% if (logged_in? && current_user.admin?) || (logged_in? && current_user == teacher) %>
            <%= link_to "Edit", edit_student_path(teacher) %>
            <% if current_user.admin? %>
              <%= link_to "Delete", student_path(teacher), method: :delete, data: {confirm: "Arm you sure you want to delete this student?"} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col s12">
    <h1 class="center-align">Student's Directory</h1>
  </div>
</div>


<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= student.name %></span>
          <p><%= student.email %></p>
          <p>Course Enrollments:
          <% if student.courses.empty? %>
            None
          <% else %>
            <ul>
              <% student.courses.each do |course| %>
                <li><%= link_to "#{course.name}", course_path(course) %></li>
              <% end %>
            </ul>
          <% end %>
          </p>
        </div>
        <div class="card-action">
          <%= link_to "View", student_path(student) %>
          <% if (logged_in? && (current_user.admin? || current_user.teacher?)) || (logged_in? && current_user == student) %>
            <%= link_to "Edit", edit_student_path(student) %>
            <% if current_user.admin? || current_user.teacher? %>
              <%= link_to "Delete", student_path(student), method: :delete, data: {confirm: "Arm you sure you want to delete this student?"} %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="col s6 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= @student.name %></span>
      <p><%= @student.email %></p>
      <p>Course Enrollments:
        <% if @student.courses.empty? %>
          None
        <% else %>
          <ul>
            <% @student.courses.each do |course| %>
              <li><%= link_to "#{course.name}", course_path(course) %></li>
            <% end %>
          </ul>
        <% end %>
        </p>
    </div>
      <div class="card-action">
        <% if (logged_in? && !@student.admin?) || (logged_in? && (current_user.admin? || current_user.teacher?)) || (logged_in? && current_user == @student) %>
          <%= link_to "Edit", edit_student_path(@student) %>
          <% if current_user != @student %>
            <%= link_to "Delete", student_path(@student), method: :delete, data: {confirm: "Arm you sure you want to delete this student?"} %>
          <% end %>
        <% end %>
      </div>
  </div>
</div>